name: Dev workflow test

env:
  SKIP: '#skip'

on:
  push:
    branches:
      - dev
jobs:
  env_variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
        # HASSKIP: ${{ contains(join(env.COMMIT_MESSAGES, ', '), env.SKIP) }}
      - name: commit messages
        id: commit_messages
        run: |
          echo "commit_message=${{ toJson(github.event.commits.*.message) }}" >> "$GITHUB_OUTPUT"
    outputs:
      # skip_present: HASSKIP
      commit_message: ${{ steps.commit_messages.outputs.commit_message }}

  dev_workflow:
    needs: [env_variables]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test output 1
        run: echo ${{ needs.env_variables.outputs.commit_message }}

  skip_test:
    if: ${{ needs.env_variables.outputs.skip_present }}
    needs: [env_variables]
    runs-on: ubuntu-latest
    steps:
      - name: skip present
        run: echo skip present
