name: Deployment pipeline

on:
  push:
    branches:
      - dev
jobs:
  env_variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
    outputs:
      commit_message: COMMIT_MESSAGES

  dev_deployment_pipeline:
    needs: [env_variables]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test output
        env:
          SKIP: #skip
        run: echo ${{ contains(join(needs.env_variables.outputs.commit_message), env.SKIP) }}
  skip_test:
    if: ${{ !contains(join(needs.env_variables.outputs.commit_message, ' '), '#skip') }}
    needs: [env_variables]
    runs-on: ubuntu-latest
    steps:
      - name: skip test
        run: echo not skipped
