name: Dev workflow test

env:
  SKIP: '#skip'

on:
  push:
    branches:
      - dev
jobs:
  env_variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          HASSKIP: ${{ contains(join(env.COMMIT_MESSAGES, ', '), env.SKIP) }}
        run: echo "$COMMIT_MESSAGES"
    outputs:
      skip_present: HASSKIP
      commit_message: COMMIT_MESSAGES
      joined_message: JOINED_MESSAGE

  dev_workflow:
    needs: [env_variables]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test output 1
        run: echo ${{ contains(needs.env_variables.outputs.joined_message, env.SKIP) }}
      - name: test output 2
        env:
          message: ${{ needs.env_variables.outputs.joined_message }}
        run: echo ${{ needs.env_variables.outputs.skip_present }}

  skip_test:
    if: ${{ needs.env_variables.outputs.skip_present }}
    needs: [env_variables]
    runs-on: ubuntu-latest
    steps:
      - name: skip test
        run: echo skip present
