name: Health Check
on:
  push:
    branches:
      - dev
jobs:
  check_health:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-sr1b.onrender.com/
          max-attempts: 3
          retry-delay: 5s
