name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  env_variables:
    runs-on: ubuntu-latest
    outputs:
      commit_message: ${{ steps.commit_messages.outputs.commit_message }}
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        id: commit_messages
        run: |
          {
            echo 'commit_message<<EOF'
            echo '${{ toJson(github.event.commits.*.message) }}'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

  simple_deployment_pipeline:
    needs: [env_variables]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: test outputs
        env:
          STR: ${{ needs.env_variables.outputs.commit_message }}
        run: echo '$STR'
      - name: test outputs 2
        env:
          str: ${{ needs.env_variables.outputs.commit_message }}
          str2: ${{ join(env.str) }}
        run: echo '$str2'
      - name: test outputs 3
        env:
          str: ${{ needs.env_variables.outputs.commit_message }}
          str2: ${{ join(env.str) }}
          str3: ${{ contains(env.str2, '#skip') }}
        run: echo "$str3"
      - name: Install dependencies
        run: npm install
      - run: npm run eslint
      - run: npm run test
      - name: build
        if: ${{ contains(needs.env_variables.outputs.commit_message, '#skip') == 'false' }}
        run: npm run build
  tag_release:
    needs: [simple_deployment_pipeline, env_variables]
    if: ${{ github.event_name == 'push' && contains(needs.env_variables.outputs.commit_message, '#skip') == 'false'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch
  notifications:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - name: success notification
        if: needs.simple_deployment_pipeline.result == 'success'
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: Cool user
          severity: info
          details: All tests passed and a new version has been deployed to production!
      - name: failure notification
        if: needs.simple_deployment_pipeline.result == 'failure'
        uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: Cool user
          severity: error
          details: There has been an error in the build!
